#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "--" > ./src/config/to_commit.txt

for file in $(git diff --cached --name-only | grep -E '\.(js|jsx)$')
do
  echo "--$file" >> ./src/config/to_commit.txt
done

npm update
